### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by codecxbox** [schnatterer/pmcaFilesystemServer#1]
Good evening sir..
Just let you know that this a what I was looking for, thanks!
I wonder if its possible to send a small thumbnail of any ARW or JPG to any Android browser..I dont know how to code, I m willing to learn though, just for that..
Or a Android app like EZ Share Wifi card app where I preview JPG before downloading from the wifi card..
Thanks in advance..

**Comment by schnatterer** [comment]
Thanks for your feedback.
Implementing thumbnails shouldn't be too hard, for android there is for example the [Android-Universal-Image-Loader](https://github.com/nostra13/Android-Universal-Image-Loader) library which works fine when displaying in an app. Not sure if it works with a web server (such as in the pmcaFilesystemServer) as well, because it's not the usual use case of an android app to start a webserver.

If you don't know how to code at all your milage for implementing this may vary, though.
I won't implement this, because I download images from my cameras via Sony's official [Imaging edge app](https://play.google.com/store/apps/details?id=com.sony.playmemories.mobile&hl=en_US) and only needed pmcaFilesystemServer for downloading 4k video which for some reason is not supported with the official app.

If you managed to implement it yourself, I'll gladly review your PR.
